### ISSUE TITLE
Reduce package size on npm

### ISSUE THREAD

**Issue by ShivamJoker** [Hinaser/jscrypto#10]
The package size on npm is around 1mb can we reduce it?

**Comment by Hinaser** [comment]
Yes it is a problem. This is because I included both es6/es5 build in the same package.
But I believe it just makes download time a bit longer. After downloading the npm package, when you import `jscrypto` into your app, unused code might be eliminated by tree-shaking mechanism provided by app bundlers/builders.
Besides, `jscrypto` does not come any dependencies. This means download time in `npm install jscrypto` is instance rather than a package whose package size is 10kb but tens of dependencies.

**Comment by ShivamJoker** [comment]
Alright thanks for clearing it up.
So if someone just used the AES what would be the dependency size?
